name: ROS2 (Mac)

# Disable for now
on:
  push:
    branches-ignore:
      - '**'
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build: # Docker is not supported on macOS and Windows.
    runs-on: macOS-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic

      # There is a bug in vcstools, where submodules are not pulled recursively
      # See https://github.com/dirk-thomas/vcstool/issues/205
      # This is fixed in master, but not in the latest release
      # Pull the latest version here
      - name: install dependencies
        run: |
          sudo pip3 install git+https://github.com/dirk-thomas/vcstool.git@7d1329f296cef4b767bf7ba0bf53a29dd3d3019c

      - name: Install dependencies
        run: |
          brew install libusb

      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: crazyflie crazyflie_interfaces
          target-ros2-distro: galactic
          colcon-defaults: |
                  {
                    "build": {
                      "packages-select": [
                          "crazyflie",
                          "crazyflie_interfaces"
                      ]
                    }
                  }