name: CMake (Windows)

on:
  push:
    branches: [ dev-crazyflie-link-cpp ]
  pull_request:
    branches: [ dev-crazyflie-link-cpp ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Boost
      shell: powershell
      run: |
        $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\hostedtoolcache\windows\Boost\1.72.0\x86_64"

    - name: Configure CMake
      run: |
        $env:BOOST_ROOT = 'C:\hostedtoolcache\windows\Boost\1.72.0\x86_64'
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
